name: Deploy Dist
on:
    push:
      branches: [ "main" ]
       #on the pull request event as the target branch is main, run the below defined jobs
    pull_request:
      branches: [ "main" ]

      paths-ignore:
        - README.md


jobs:
    #job1
    test:
        runs-on: ubuntu-latest    
                    # steps that GitHub has to do to complete the job
        steps:
                - name: Get Code
                # checkout to the current branch
                  uses: actions/checkout@v4
                - name: Install Node 20
                # setting up the node environment
                  uses: actions/setup-node@v4
                  with:
                    node-version: 20
                - name: print the node version
                  run: node -v

                  #to make the deployment process fast 
                - name: Cache Dependencies
                  uses: actions/cache@v4
                  with:
                    path: ~/.npm
                    # ubuntu-node-334224(value)
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}


                - name: Intall the dependencies
                  run: npm install

                - name: Run Test
                #will run the test script from the package.json
                  run: npm run test
    #job2
    deploy: 
            #for running the job sequentially
            needs: test
            runs-on: ubuntu-latest    
                    # steps that GitHub has to do to complete the job
            steps:
                - name: Get Code
                # checkout to the current branch
                  uses: actions/checkout@v4
                - name: Install Node 20
                # setting up the node environment
                  uses: actions/setup-node@v4
                  with:
                    node-version: 20
                - name: Cache Dependencies
                  uses: actions/cache@v4
                  with:
                    path: ~/.npm
                      # ubuntu-node-334224(value)
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  
                - name: Intall the dependencies
                  run: npm install
                
                - name: Build Project
                  run: npm run build
                - name: Deploy
                  run: echo "Deploy Successful"
                