name: Greeting
# on: push
on: push
jobs:
    test:
        runs-on: ubuntu-latest    
        strategy:
                matrix:
                  # the version of node that can be executable
                  node-version: [18.x, 20.x, 22.x]
          
              # steps that GitHub has to do to complete the job
        steps:
                # checkout to the current branch
                - uses: actions/checkout@v4
                - name: Use Node.js ${{ matrix.node-version }}
                # setting up the node environment
                  uses: actions/setup-node@v4
                  with:
                    # the versions to be set up are
                    node-version: ${{ matrix.node-version }}
                    cache: 'npm'
                - name: print the node version
                  run: node -v

                - name: Intall the dependencies
                  run: npm install

                - name: Run Test
                #will run the test script from the package.json
                  run: npm run test
                
                - name: Get Code
          
              
            